### ISSUE TITLE
keyed-vals-redis-2.3.5 build failure on hackage

### ISSUE THREAD

**Issue by adetokunbo** [adetokunbo/keyed-vals#33]
[1 of 2] Compiling KeyedVals.Handle.Redis.Internal ( src/KeyedVals/Handle/Redis/Internal.hs, dist/build/KeyedVals/Handle/Redis/Internal.o, dist/build/KeyedVals/Handle/Redis/Internal.dyn_o )

src/KeyedVals/Handle/Redis/Internal.hs:149:27: error: [GHC-83865]
    " Couldn't match expected type: NonEmpty B.ByteString
                  with actual type: [Key]
    " In the second argument of hmget, namely dictKeys
      In the second argument of doFetch, namely (hmget key dictKeys)
      In the first argument of (>>=), namely
        doFetch conn (hmget key dictKeys)
    |
149 |   doFetch conn (hmget key dictKeys) >>= \case
    |                           ^^^^^^^^

src/KeyedVals/Handle/Redis/Internal.hs:172:51: error: [GHC-83865]
    " Couldn't match type Integer with Either Reply a0
      Expected: Val -> Redis (Either Reply a0)
        Actual: Val -> Redis Integer
    " In the result of a function call
      In the second argument of ($), namely hset key dictKey value
      In the expression: doStore' conn $ hset key dictKey value
    |
172 | hSaveTo' conn key dictKey value = doStore' conn $ hset key dictKey value
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^

src/KeyedVals/Handle/Redis/Internal.hs:172:60: error: [GHC-83865]
    " Couldn't match type B.ByteString
                     with NonEmpty (B.ByteString, B.ByteString)
      Expected: NonEmpty (B.ByteString, B.ByteString)
        Actual: Key
    " In the second argument of hset, namely dictKey
      In the second argument of ($), namely hset key dictKey value
      In the expression: doStore' conn $ hset key dictKey value
    |
172 | hSaveTo' conn key dictKey value = doStore' conn $ hset key dictKey value
    |                                                            ^^^^^^^

src/KeyedVals/Handle/Redis/Internal.hs:192:57: error: [GHC-83865]
    " Couldn't match expected type: NonEmpty
                                      (B.ByteString, B.ByteString)
                  with actual type: [(Key, Val)]
    " In the second argument of ($), namely Map.toList dict
      In the second argument of ($), namely
        hmset key $ Map.toList dict
      In the expression: doStore' conn $ hmset key $ Map.toList dict
    |
192 | hUpdateKVs' conn key dict = doStore' conn $ hmset key $ Map.toList dict
    |                                                         ^^^^^^^^^^^^^^^

src/KeyedVals/Handle/Redis/Internal.hs:200:58: error: [GHC-83865]
    " Couldn't match expected type: NonEmpty B.ByteString
                  with actual type: [Key]
    " In the second argument of ($), namely NonEmpty.toList ks
      In the second argument of ($), namely del $ NonEmpty.toList ks
      In the expression: doStore' conn $ del $ NonEmpty.toList ks
    |
200 | hDeleteSelected' conn (AllOf ks) = doStore' conn $ del $ NonEmpty.toList ks
    |                                                          ^^^^^^^^^^^^^^^^^^

src/KeyedVals/Handle/Redis/Internal.hs:214:76: error: [GHC-83865]
    " Couldn't match expected type: NonEmpty B.ByteString
                  with actual type: [Key]
    " In the second argument of ($), namely
        NonEmpty.toList dictKeys
      In the second argument of ($), namely
        hdel key $ NonEmpty.toList dictKeys
      In the expression:
        doStore' conn $ hdel key $ NonEmpty.toList dictKeys
    |
214 | hDeleteSelectedKVs' conn key (AllOf dictKeys) = doStore' conn $ hdel key $ NonEmpty.toList dictKeys
    |                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^
Failed to install keyed-vals-redis-0.2.3.5
Error: cabal: Some packages failed to install:
keyed-vals-redis-0.2.3.5-9fiKCIoi0c28PEtrsFjm6s failed during the building
phase. The exception was:
ExitFailure 1

**Comment by juhp** [comment]
This fails in Stackage Nightly with hedis-0.15:
```
       Building library for keyed-vals-redis-0.2.4.0...           
       [1 of 2] Compiling KeyedVals.Handle.Redis.Internal                                                                                                                                                                                                                                                                                 
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:148:27: error: [GHC-83865]                  
           • Couldn't match expected type: [B.ByteString]                                                                                                                                   
                         with actual type: NonEmpty Key                                                       
           • In the second argument of ‘hmget’, namely ‘dictKeys’                                             
             In the second argument of ‘doFetch’, namely ‘(hmget key dictKeys)’                                                                                      
             In the first argument of ‘(>>=)’, namely                    
               ‘doFetch conn (hmget key dictKeys)’                                                                                  
           |                                                                                                                        
       148 |   doFetch conn (hmget key dictKeys) >>= \case               
           |                           ^^^^^^^^                                                                                     
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:171:51: error: [GHC-83865]                                                                                                                                
           • Couldn't match expected type: Redis (Either Reply a0)                                                                                
                         with actual type: B.ByteString -> m0 (f0 Integer)                                                                        
           • Probable cause: ‘hset’ is applied to too few arguments                                                                                                                                                                                                                                                                       
             In the second argument of ‘($)’, namely                                                                                                                                                                        
               ‘hset key (NonEmpty.singleton (dictKey, value))’                                               
             In the expression:                                                                                                                                                             
               doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))
             In an equation for ‘hSaveTo'’:                                       
                 hSaveTo' conn key dictKey value                                  
                   = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                                                  
           |                                                                      
       171 | hSaveTo' conn key dictKey value = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                        
           |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
                                                                                                              
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:171:61: error: [GHC-83865]                                                                                                                                
           • Couldn't match expected type ‘B.ByteString’                                                                                                                                                                                                                                                                                  
                         with actual type ‘NonEmpty (Key, Val)’                                                                                                                                                             
           • In the second argument of ‘hset’, namely                                                                                                                                       
               ‘(NonEmpty.singleton (dictKey, value))’                                                        
             In the second argument of ‘($)’, namely                                                                                                                                        
               ‘hset key (NonEmpty.singleton (dictKey, value))’                                               
             In the expression:                                                                               
               doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))
           |                                           
       171 | hSaveTo' conn key dictKey value = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                        
           |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                              
                                                                                                                                                                                                                            
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:193:41: error: [GHC-83865]                                                                                                                                
           • Couldn't match expected type: [(B.ByteString, B.ByteString)]         
                         with actual type: NonEmpty (Key, Val)                                                
           • In the second argument of ‘hmset’, namely ‘x’                                                    
             In the second argument of ‘($)’, namely ‘hmset key x’                
             In the expression: doStore' conn $ hmset key x                       
           |                                                                                                  
       193 |     Just x -> doStore' conn $ hmset key x                                                        
           |                                         ^                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:202:56: error: [GHC-83865]                                                                                                                                
           • Couldn't match expected type: [B.ByteString]       
                         with actual type: NonEmpty Key                           
           • In the first argument of ‘del’, namely ‘ks’                                                                            
             In the second argument of ‘($)’, namely ‘del ks’                     
             In the expression: doStore' conn $ del ks                                                                                                               
           |                                                                                                                                                         
       202 | hDeleteSelected' conn (AllOf ks) = doStore' conn $ del ks            
           |                                                        ^^                                                                                                                                                                                                                                                                    
                                                                                  
       /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:216:74: error: [GHC-83865]                                                                                                                                
           • Couldn't match expected type: [B.ByteString]                         
                         with actual type: NonEmpty Key                           
           • In the second argument of ‘hdel’, namely ‘dictKeys’                  
             In the second argument of ‘($)’, namely ‘hdel key dictKeys’
             In the expression: doStore' conn $ hdel key dictKeys                 
           |                                                                      
       216 | hDeleteSelectedKVs' conn key (AllOf dictKeys) = doStore' conn $ hdel key dictKeys                                                                       
           |                                                                          ^^^^^^^^ 
```

So perhaps you need `hedis >= 0.16` lowerbound?

Also *if* [0.2.3.6](https://hackage.haskell.org/package/keyed-vals-redis-0.2.3.6) is a bad release, it would be better to mark deprecated in hackage metadata?

**Comment by adetokunbo** [comment]
> This fails in Stackage Nightly with hedis-0.15:
> 
> ```
>        Building library for keyed-vals-redis-0.2.4.0...           
>        [1 of 2] Compiling KeyedVals.Handle.Redis.Internal                                                                                                                                                                                                                                                                                 
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:148:27: error: [GHC-83865]                  
>            • Couldn't match expected type: [B.ByteString]                                                                                                                                   
>                          with actual type: NonEmpty Key                                                       
>            • In the second argument of ‘hmget’, namely ‘dictKeys’                                             
>              In the second argument of ‘doFetch’, namely ‘(hmget key dictKeys)’                                                                                      
>              In the first argument of ‘(>>=)’, namely                    
>                ‘doFetch conn (hmget key dictKeys)’                                                                                  
>            |                                                                                                                        
>        148 |   doFetch conn (hmget key dictKeys) >>= \case               
>            |                           ^^^^^^^^                                                                                     
>                                                                                                                                     
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:171:51: error: [GHC-83865]                                                                                                                                
>            • Couldn't match expected type: Redis (Either Reply a0)                                                                                
>                          with actual type: B.ByteString -> m0 (f0 Integer)                                                                        
>            • Probable cause: ‘hset’ is applied to too few arguments                                                                                                                                                                                                                                                                       
>              In the second argument of ‘($)’, namely                                                                                                                                                                        
>                ‘hset key (NonEmpty.singleton (dictKey, value))’                                               
>              In the expression:                                                                                                                                                             
>                doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))
>              In an equation for ‘hSaveTo'’:                                       
>                  hSaveTo' conn key dictKey value                                  
>                    = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                                                  
>            |                                                                      
>        171 | hSaveTo' conn key dictKey value = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                        
>            |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
>                                                                                                               
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:171:61: error: [GHC-83865]                                                                                                                                
>            • Couldn't match expected type ‘B.ByteString’                                                                                                                                                                                                                                                                                  
>                          with actual type ‘NonEmpty (Key, Val)’                                                                                                                                                             
>            • In the second argument of ‘hset’, namely                                                                                                                                       
>                ‘(NonEmpty.singleton (dictKey, value))’                                                        
>              In the second argument of ‘($)’, namely                                                                                                                                        
>                ‘hset key (NonEmpty.singleton (dictKey, value))’                                               
>              In the expression:                                                                               
>                doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))
>            |                                           
>        171 | hSaveTo' conn key dictKey value = doStore' conn $ hset key (NonEmpty.singleton (dictKey, value))                                                        
>            |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                              
>                                                                                                                                                                                                                             
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:193:41: error: [GHC-83865]                                                                                                                                
>            • Couldn't match expected type: [(B.ByteString, B.ByteString)]         
>                          with actual type: NonEmpty (Key, Val)                                                
>            • In the second argument of ‘hmset’, namely ‘x’                                                    
>              In the second argument of ‘($)’, namely ‘hmset key x’                
>              In the expression: doStore' conn $ hmset key x                       
>            |                                                                                                  
>        193 |     Just x -> doStore' conn $ hmset key x                                                        
>            |                                         ^                                                                                                                                                                                                                                                                                    
>                                                                                                                                                                                                                                                                         
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:202:56: error: [GHC-83865]                                                                                                                                
>            • Couldn't match expected type: [B.ByteString]       
>                          with actual type: NonEmpty Key                           
>            • In the first argument of ‘del’, namely ‘ks’                                                                            
>              In the second argument of ‘($)’, namely ‘del ks’                     
>              In the expression: doStore' conn $ del ks                                                                                                               
>            |                                                                                                                                                         
>        202 | hDeleteSelected' conn (AllOf ks) = doStore' conn $ del ks            
>            |                                                        ^^                                                                                                                                                                                                                                                                    
>                                                                                   
>        /home/curators/work/unpack-dir/unpacked/keyed-vals-redis-0.2.4.0-5b7c030d58d4fa77cf2dd92bd65e9857cd289233ef4c2075cd26794b3aa328b3/src/KeyedVals/Handle/Redis/Internal.hs:216:74: error: [GHC-83865]                                                                                                                                
>            • Couldn't match expected type: [B.ByteString]                         
>                          with actual type: NonEmpty Key                           
>            • In the second argument of ‘hdel’, namely ‘dictKeys’                  
>              In the second argument of ‘($)’, namely ‘hdel key dictKeys’
>              In the expression: doStore' conn $ hdel key dictKeys                 
>            |                                                                      
>        216 | hDeleteSelectedKVs' conn key (AllOf dictKeys) = doStore' conn $ hdel key dictKeys                                                                       
>            |                                                                          ^^^^^^^^ 
> ```
> 
> So perhaps you need `hedis >= 0.16` lowerbound?
> 
> Also _if_ [0.2.3.6](https://hackage.haskell.org/package/keyed-vals-redis-0.2.3.6) is a bad release, it would be better to mark deprecated in hackage metadata?

Thanks, this should be fixed in a new release 0.2.5.0.   Also marked the `<0.2.3.6 || >=0.2.5.0` as the preferred range

**Comment by juhp** [comment]
Thanks - I think it would make sense to do an upperbound revision for 0.2.3.5?  (I don't think it can build with hedis >= 0.16?)
